name: env_multiviewVAE
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.*
  - numpy
  - pip
  - scikit-learn
  - pandas
  - pytorch
  - pytorch-lightning
  - torchvision
  - tensorboard
  - matplotlib
  - statsmodels
  # - torchaudio
  ### Optional:
  # - jupyter
  # - jupyterlab
